# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
#
# Mounting volumes is not supported, just run the same commands in the CI container
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: dkoshkin/golang-ci:1.10.3-stretch-1.0.0
    working_directory: /go/src/github.com/dkoshkin/gofer
    steps:
      - checkout
      - setup_remote_docker

      # specify any bash command here prefixed with `run: `
      - run: 
          name: Vendor Go dependencies
          command: make vendor-local
      - run: 
          name: Unit test
          command: make test-local
      - run: 
          name: Build container 
          command: make build-container
      - run: 
          name: Docker push 
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS && make push
      - run:
          name: Release container and binary
          command: | 
            if [[ -n "$CIRCLE_TAG" ]]
            then
              VERSION=$CIRCLE_TAG make tag-and-push
              TARGET_GOOS=darwin TARGE_GOARCH=amd64 make build-binary-local
              TARGET_GOOS=linux TARGE_GOARCH=amd64 make build-binary-local
              ghr -draft -u "$CIRCLE_PROJECT_USERNAME" "$CIRCLE_TAG" bin/
            fi

deployment:
  fake_deploy_for_cci2:
    tag: /.*/
    commands:
      - echo "make tags run in 2.0"