# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
#
# Mounting volumes is not supported, just run the same commands in the CI container
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.11.3
    steps:
      - checkout
      - setup_remote_docker

      # specify any bash command here prefixed with run:
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}

      - run: 
          name: Unit test
          command: make test-local
      - run: 
          name: Build container 
          command: make build-container
      - run: 
          name: Docker push 
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS && make push
      - run:
          name: Release container and binary
          environment:
            GHR_VERSION: v0.12.0
          command: | 
            if [[ -n "$CIRCLE_TAG" ]]
            then
              wget https://github.com/tcnksm/ghr/releases/download/v0.12.0/ghr_v0.12.0_linux_amd64.tar.gz -O ghr.tar.gz && tar xvzf ghr.tar.gz && rm ghr.tar.gz
              VERSION=$CIRCLE_TAG make tag-and-push
              VERSION=stable make tag-and-push
              GOOS=darwin GOARCH=amd64 make build-binary-local
              GOOS=linux GOARCH=amd64 make build-binary-local
              ./ghr_v0.12.0_linux_amd64/ghr -draft -u "$CIRCLE_PROJECT_USERNAME" "$CIRCLE_TAG" bin/
            fi

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

deployment:
  fake_deploy_for_cci2:
    tag: /.*/
    commands:
      - echo "make tags run in 2.0"