# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: dkoshkin/golang-ci:1.10.3-stretch-1
    working_directory: /go/src/github.com/dkoshkin/gofer
    steps:
      - checkout
      - setup_remote_docker

      # specify any bash command here prefixed with `run: `
      - run: dep ensure -v
      - run: go test -v ./cmd/... ./pkg/...

      - run: make build

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS 
      - run: make push

      - run:
          name: make release
          command: | 
            if [[ -n "$CIRCLE_TAG" ]]
            then
              TAG=$CIRCLE_TAG make release
              #ghr -draft -u "$CIRCLE_PROJECT_USERNAME" "${CIRCLE_TAG}" release/
            fi

deployment:
  fake_deploy_for_cci2:
    tag: /.*/
    commands:
      - echo "make tags run in 2.0"