# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
#
# TODO figure out why make targest aren't working
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: dkoshkin/golang-ci:1.10.3-stretch-1
    working_directory: /go/src/github.com/dkoshkin/gofer
    steps:
      - checkout
      - setup_remote_docker

      # specify any bash command here prefixed with `run: `
      - run: 
          name: Vendor Go dependencies
          command: dep ensure -v
      - run: 
          name: Unit test
          command: go test -v ./cmd/... ./pkg/...
      - run: 
          name: Build container 
          command: make build-container
      - run: 
          name: Docker push 
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS && make push
      - run:
          name: Release container and binary
          command: | 
            if [[ -n "$CIRCLE_TAG" ]]
            then
              VERSION=$CIRCLE_TAG make tag-and-push
              GOOS=darwin GOARCH=amd64 go build -o bin/gofer-darwin-amd64 main.go
              GOOS=linux GOARCH=amd64 go build -o bin/gofer-linux-amd64 main.go
              ghr -draft -u "$CIRCLE_PROJECT_USERNAME" "$CIRCLE_TAG" bin/
            fi

deployment:
  fake_deploy_for_cci2:
    tag: /.*/
    commands:
      - echo "make tags run in 2.0"