apiversion: v0.1
dependencies:
- name: alpine
  type: docker
  version: "3.6"
- name: google/cadvisor
  type: docker
  version: v0.28.1
- name: google/cadvisor
  type: docker
  version: v0.29.2
  mask: v0.29.[0-9]+
- name: cadvisor
  type: docker
  version: v0.28.1
  mask: v0.29.[0-9]+
- name: gcr.io/google-containers/kube-apiserver
  type: docker
  version: v1.9.6
  mask: v1.9.[0-9]+
- name: quay.io/coreos/etcd
  type: docker
  version: v3.1.13
  mask: v3.1.[0-9]+
- name: https://github.com/kubernetes/kubernetes
  type: manual
  version: v1.9.6
  mask: v1.9.[0-9]+